/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cruz.mx.monitoreo.view;

import com.cruz.mx.monitoreo.beans.Proceso;
import com.cruz.mx.monitoreo.enums.DIALOG_STATE;
import com.cruz.mx.monitoreo.view.slider.RangeSliderDemo;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author acruzb
 */
public class DialogProceso extends javax.swing.JDialog{

    private final RangeSliderDemo rangerSlider;
    public static final String RANGE_SEPARATOR = " - ";
    private final Principal principal;
    private DIALOG_STATE mode;
    private Proceso proceso;
    /**
     * Creates new form DialogProceso
     * @param parent
     * @param modal
     */
    public DialogProceso(Principal parent, boolean modal) {
        super(parent, modal);
        this.principal = parent;
        initComponents();
        panelSlider.setLayout(new BorderLayout());
        rangerSlider = new RangeSliderDemo();
        panelSlider.add(rangerSlider, BorderLayout.CENTER);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                emptyData();
            }
        });
    }

    private boolean validateEmptyField(JTextField field){
        boolean result = !"".equals(field.getText());
        if(!result){
            JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos.", "Validación", JOptionPane.WARNING_MESSAGE);
            field.requestFocus();
        }
        return result;
    }
    
    public void setMode(DIALOG_STATE mode){
        this.mode = mode;
        setVisible(true);
        setLocationRelativeTo(principal);
        btnAgregar.setText((mode.equals(DIALOG_STATE.NEW)? "Agregar": "Actualizar"));
        setTitle((mode.equals(DIALOG_STATE.NEW)? "Nueva preferencia": "Actualizar preferencia"));
        if(mode.equals(DIALOG_STATE.NEW)){
            btnEliminar.setVisible(false);
        }
        else{
            btnEliminar.setVisible(true);
        }
    }
    
    public void setData(Proceso proceso){
        this.proceso = proceso;
        comboSistema.setSelectedItem(proceso.getSistema());
        comboFrecuencia.setSelectedItem(proceso.getFrecuencia());
        textFieldAlerta.setText(String.valueOf(proceso.getNumAlerta()));
        textFieldTexto.setText(proceso.getTextoBusqueda());
        textFieldMensaje.setText(proceso.getMensaje());
        String rango[] = proceso.getRangoTiempo().split(RANGE_SEPARATOR);
        rangerSlider.setTimeRange(Integer.valueOf(rango[0].split(":")[0]), Integer.valueOf(rango[1].split(":")[0]));
    }
    
    private void emptyData(){
        textFieldAlerta.setText("");
        textFieldMensaje.setText("");
        textFieldTexto.setText("");
        comboSistema.setSelectedIndex(0);
        comboFrecuencia.setSelectedIndex(0);
        rangerSlider.setTimeRange(9, 19);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboSistema = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboFrecuencia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldAlerta = new javax.swing.JTextField();
        textFieldTexto = new javax.swing.JTextField();
        textFieldMensaje = new javax.swing.JTextField();
        panelSlider = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sistema");

        comboSistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Core Banca Digital", "JVC" }));

        jLabel2.setText("Frecuencia (mins)");

        comboFrecuencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "5", "10", "15", "20", "30", "40", "50", "60", "120" }));

        jLabel3.setText("Rango de tiempo");

        jLabel4.setText("Número alerta");

        jLabel5.setText("Texto de búsqueda");

        jLabel6.setText("Mensaje");

        javax.swing.GroupLayout panelSliderLayout = new javax.swing.GroupLayout(panelSlider);
        panelSlider.setLayout(panelSliderLayout);
        panelSliderLayout.setHorizontalGroup(
            panelSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSliderLayout.setVerticalGroup(
            panelSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboSistema, 0, 239, Short.MAX_VALUE)
                                    .addComponent(comboFrecuencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldTexto)
                                    .addComponent(textFieldMensaje)
                                    .addComponent(textFieldAlerta, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(validateEmptyField(textFieldAlerta) && validateEmptyField(textFieldMensaje) && validateEmptyField(textFieldTexto)){
            String numAlerta = textFieldAlerta.getText();
            String mensaje = textFieldMensaje.getText();
            String texto = textFieldTexto.getText();
            int frecuencia = Integer.parseInt(comboFrecuencia.getSelectedItem().toString());
            String sistema = comboSistema.getSelectedItem().toString();
            String rango = rangerSlider.getDesde() + RANGE_SEPARATOR + rangerSlider.getHasta();
            if(!numAlerta.matches("\\d+")){
                JOptionPane.showMessageDialog(this, "Favor de ingresar un número entero.", "Campo incorrecto", JOptionPane.ERROR_MESSAGE);
                textFieldAlerta.requestFocus();
                return;
            }
            if(mode.equals(DIALOG_STATE.NEW)){
                Proceso proceso = new Proceso(sistema, frecuencia, rango, Integer.parseInt(numAlerta), texto, mensaje);
                principal.addProcesoTabla(proceso);
            }
            else{
                proceso.setFrecuencia(frecuencia);
                proceso.setMensaje(mensaje);
                proceso.setNumAlerta(Integer.parseInt(numAlerta));
                proceso.setRangoTiempo(rango);
                proceso.setSistema(sistema);
                proceso.setTextoBusqueda(texto);
                proceso.setRunning(false);//
                principal.updateProcesoTabla(proceso);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la preferencia?", "Eliminar preferencia", JOptionPane.YES_NO_OPTION)){
            proceso.setRunning(false);
            principal.deleteProcesoTabla(proceso);
            this.dispose();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> comboFrecuencia;
    private javax.swing.JComboBox<String> comboSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelSlider;
    private javax.swing.JTextField textFieldAlerta;
    private javax.swing.JTextField textFieldMensaje;
    private javax.swing.JTextField textFieldTexto;
    // End of variables declaration//GEN-END:variables
}
