/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cruz.mx.monitoreo.view;

import com.cruz.mx.monitoreo.enums.OSType;
import com.cruz.mx.monitoreo.utils.SistemaOperativo;
import java.awt.Color;
import java.awt.GraphicsDevice;
import static java.awt.GraphicsDevice.WindowTranslucency.PERPIXEL_TRANSPARENT;
import static java.awt.GraphicsDevice.WindowTranslucency.TRANSLUCENT;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author acruzb
 */
public class WindowXRP extends javax.swing.JDialog {

    /**
     * Creates new form WindowXRP
     *
     * @param bitsoBusiness
     */
    public WindowXRP() {
        setUndecorated(true);
        setSize(300, 200);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        initComponents();
        addComponentListener(new ComponentAdapter() {
            Point lastLocation;

            @Override
            public void componentMoved(ComponentEvent e) {
                if (lastLocation == null && isVisible()) {
                    lastLocation = getLocation();
                } else {
                    Point newLocation = getLocation();
                    int dx = newLocation.x - lastLocation.x;
                    int dy = newLocation.y - lastLocation.y;
                    setLocation(getX() + dx, getY() + dy);
                    lastLocation = newLocation;
                }
            }
        });
    }

    public void setXRPMXN(double low, double precio, double high) {
        this.labelPrecioXRPLow.setText(String.format("$%.2f", low));
        this.labelPrecioXRP.setText(String.format("$%.2f", precio));
        this.labelPrecioXRPHigh.setText(String.format("$%.2f", high));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPrecioXRPLow = new javax.swing.JLabel();
        labelPrecioXRPHigh = new javax.swing.JLabel();
        labelPrecioXRP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        labelPrecioXRPLow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPrecioXRPLow.setForeground(new java.awt.Color(255, 0, 0));
        labelPrecioXRPLow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrecioXRPLow.setText("$35.80");

        labelPrecioXRPHigh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPrecioXRPHigh.setForeground(new java.awt.Color(102, 204, 0));
        labelPrecioXRPHigh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrecioXRPHigh.setText("$45.01");

        labelPrecioXRP.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelPrecioXRP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrecioXRP.setText("$40.50");
        labelPrecioXRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickDoble(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrecioXRPLow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecioXRP, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecioXRPHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioXRPLow)
                    .addComponent(labelPrecioXRPHigh)
                    .addComponent(labelPrecioXRP))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseClickDoble(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickDoble
        if (evt.getClickCount() == 2) {
            setVisible(false);
        }
    }//GEN-LAST:event_mouseClickDoble

    /**
     * @param args the command line arguments
     */
    public void mostrar() {
        // Determine what the GraphicsDevice can support.
        GraphicsEnvironment ge
                = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        final boolean isTranslucencySupported
                = gd.isWindowTranslucencySupported(TRANSLUCENT);

        //If shaped windows aren't supported, exit.
        if (!gd.isWindowTranslucencySupported(PERPIXEL_TRANSPARENT)) {
            System.err.println("Shaped windows are not supported");
            System.exit(0);
        }

        //If translucent windows aren't supported, 
        //create an opaque window.
        if (!isTranslucencySupported) {
            System.out.println(
                    "Translucency is not supported, creating an opaque window");
        }

        final WindowXRP sw = this;
        // Create the GUI on the event-dispatching thread
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Set the window to 70% translucency, if supported.
                if (isTranslucencySupported) {
                    sw.setOpacity(0.7f);
                }
                // Display the window.
                sw.setVisible(true);
                sw.setAlwaysOnTop(true);
                if(SistemaOperativo.getOperatingSystemType().equals(OSType.MacOS)){
                    sw.setLocation(getX(), 20);
                }
                else{
                    sw.setLocation(getX(), 0);
                }
            }
        });
    }

    public static void main(String[] args) {
        WindowXRP d = new WindowXRP();
        d.mostrar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPrecioXRP;
    private javax.swing.JLabel labelPrecioXRPHigh;
    private javax.swing.JLabel labelPrecioXRPLow;
    // End of variables declaration//GEN-END:variables
}
